### ISSUE TITLE
filter is not working properly (V 1.0.3)

### ISSUE THREAD

**Issue by notspecified** [derqurps/noefinderlein#2]
when choosing check/uncheck all at the filter mode only the upper 8 icons are selected, the other (lower 5) keep untouched. -at least with android N!

with version 1.0.2 and android 5.1.1 check/uncheck all really selects all filter possibilities, which is in my opinion the proper behavior.
![screenshot_20160418-180328](https://cloud.githubusercontent.com/assets/5119558/14611168/3478b740-0591-11e6-8793-f74bb844a735.png)
![screenshot_20160418-180332](https://cloud.githubusercontent.com/assets/5119558/14611242/7865c2f4-0591-11e6-8d1d-872aaa3c622b.png)

**Comment by derqurps** [comment]
This is the intentional behaviour. The top items are OR items which are combined with the bottom items with an AND. And the bottom items are also with AND combined. 
I think this makes more sense to give the user the ability to ie. search for: Today I want to visit a Stift or a Museum, but show me only these where Dogs are allowed. "(Museum OR Stift) AND Dogs" 
Or "(Museum OR Stift) AND Dogs AND TopLocation"

But normal queries are also allowed: ie search only for locations where Dogs are allowed. 

With this behavior it does not make sense to activate all bottom items with a click on "all on", because then only the items will be shown, which have all of the following: top, Hund, Rollstuhl, Kinderwagen and gruppe. Which is only one item (of 325)

I thought this would make more sense than the behavior before. I must admit that it is not the most intuitive behavior but it makes more sense. 

If you happen to have an idea how to make this visually understandable, please share your ideas!

**Comment by derqurps** [comment]
I just changed the layout of the filter a little bit - maybe it is now more understandable?

![auswahl_008](https://cloud.githubusercontent.com/assets/4160493/14760488/c0272832-0945-11e6-8436-2bfa7215fd20.png)
![auswahl_009](https://cloud.githubusercontent.com/assets/4160493/14760489/c8c5aebe-0945-11e6-8997-6fe497f8660c.png)

**Comment by notspecified** [comment]
that looks good IMHO! with this seperation it's clear why the lower 5 icons are not affected by the upper checkbox.

**Comment by derqurps** [comment]
Thanks for your feedback!

**Comment by derqurps** [comment]
Fixed in 1.0.4
